
### all tracks

GET {{hostname}}/api/rally/tracks
Accept: application/json

> {%
    client.global.set("trackId", response.body[0].id);
%}

### first track

GET {{hostname}}/api/rally/tracks/{{trackId}}
Accept: application/json

### create track

POST {{hostname}}/api/rally/tracks
Accept: application/json
Content-Type: application/json

{
    "name": "First",
    "width": 1000.0,
    "height": 1000.0,
    "checkpoints": [
        {
            "start": {
                "x": 158.88194259486227,
                "y": 109.1750816477536
            },
            "end": {
                "x": 156.25361648716898,
                "y": 19.21346815693398
            }
        },
        {
            "start": {
                "x": 136.467822336758,
                "y": 133.1272926746821
            },
            "end": {
                "x": 46.529797292148274,
                "y": 136.46670146594292
            }
        },
        {
            "start": {
                "x": 170.88580868068402,
                "y": 311.4402850809835
            },
            "end": {
                "x": 86.16582706150348,
                "y": 341.8133770283915
            }
        },
        {
            "start": {
                "x": 382.65835409218914,
                "y": 315.8482124279388
            },
            "end": {
                "x": 466.04110879843586,
                "y": 349.7202690173737
            }
        },
        {
            "start": {
                "x": 624.8751443644882,
                "y": 394.0669462045246
            },
            "end": {
                "x": 537.430275557387,
                "y": 372.7738741079754
            }
        },
        {
            "start": {
                "x": 273.7547881253322,
                "y": 635.2430844050373
            },
            "end": {
                "x": 285.2625458590428,
                "y": 545.981830145744
            }
        },
        {
            "start": {
                "x": 190.6438881931657,
                "y": 740.2484435855847
            },
            "end": {
                "x": 106.4115317287092,
                "y": 771.9487610042592
            }
        },
        {
            "start": {
                "x": 414.8999694744151,
                "y": 885.9142067395227
            },
            "end": {
                "x": 420.182550056835,
                "y": 975.759041551493
            }
        },
        {
            "start": {
                "x": 831.2569421267318,
                "y": 884.171934314367
            },
            "end": {
                "x": 826.7264563107681,
                "y": 974.0578325313362
            }
        },
        {
            "start": {
                "x": 869.1291386858696,
                "y": 847.1966543764977
            },
            "end": {
                "x": 959.0977900250678,
                "y": 844.8214120297524
            }
        },
        {
            "start": {
                "x": 807.6371357305293,
                "y": 705.9642471311878
            },
            "end": {
                "x": 870.6697490350956,
                "y": 641.7233749391248
            }
        },
        {
            "start": {
                "x": 776.0656878427153,
                "y": 295.1180102786981
            },
            "end": {
                "x": 848.1734478994719,
                "y": 348.9740307369271
            }
        },
        {
            "start": {
                "x": 764.545050332518,
                "y": 172.3865508854994
            },
            "end": {
                "x": 825.3707060021981,
                "y": 106.05224895690841
            }
        },
        {
            "start": {
                "x": 623.3135338474324,
                "y": 113.5079074373389
            },
            "end": {
                "x": 627.6198157619426,
                "y": 23.6109890470361
            }
        }
    ],
    "positions": [
        {
            "location": {
                "x": 184.76012262955982,
                "y": 81.79973068651907
            },
            "heading": -3.1663957978892965
        },
        {
            "location": {
                "x": 183.85076725056413,
                "y": 45.144342034383044
            },
            "heading": -3.1663957978892965
        },
        {
            "location": {
                "x": 221.41809691199512,
                "y": 81.00137866117893
            },
            "heading": -3.1603394248413483
        },
        {
            "location": {
                "x": 220.730755561127,
                "y": 44.3411548987433
            },
            "heading": -3.1603394248413483
        },
        {
            "location": {
                "x": 258.08023398369915,
                "y": 80.42505428763707
            },
            "heading": -3.1542830517934006
        },
        {
            "location": {
                "x": 257.61493187232486,
                "y": 43.761340095133164
            },
            "heading": -3.1542830517934006
        },
        {
            "location": {
                "x": 294.7451890942641,
                "y": 80.07077870520607
            },
            "heading": -3.148226678745453
        },
        {
            "location": {
                "x": 294.5019432894522,
                "y": 43.404918890892986
            },
            "heading": -3.148226678745453
        },
        {
            "location": {
                "x": 331.4116173899139,
                "y": 79.93856490855342
            },
            "heading": -3.1421703056975048
        },
        {
            "location": {
                "x": 331.39043681380906,
                "y": 43.27190435938883
            },
            "heading": -3.1421703056975048
        },
        {
            "location": {
                "x": 368.07817396283656,
                "y": 80.02841774722037
            },
            "heading": -3.136113932649557
        },
        {
            "location": {
                "x": 368.27905939233267,
                "y": 43.362301379534074
            },
            "heading": -3.136113932649557
        },
        {
            "location": {
                "x": 404.743513900519,
                "y": 80.34033392544552
            },
            "heading": -3.1300575596016094
        },
        {
            "location": {
                "x": 405.1664579672305,
                "y": 43.67610663560754
            },
            "heading": -3.1300575596016094
        },
        {
            "location": {
                "x": 441.4062923350699,
                "y": 80.87430200228755
            },
            "heading": -3.124001186553661
        },
        {
            "location": {
                "x": 442.0512795256019,
                "y": 44.21330861737624
            },
            "heading": -3.124001186553661
        },
        {
            "location": {
                "x": 478.0651644925524,
                "y": 81.63030239203908
            },
            "heading": -3.1179448135057135
        },
        {
            "location": {
                "x": 478.93217114907,
                "y": 44.97388762051469
            },
            "heading": -3.1179448135057135
        },
        {
            "location": {
                "x": 514.7187857423144,
                "y": 82.60830736495427
            },
            "heading": -3.111888440457766
        },
        {
            "location": {
                "x": 515.8077800634101,
                "y": 45.9578157473361
            },
            "heading": -3.111888440457766
        },
        {
            "location": {
                "x": 551.3658116463006,
                "y": 83.80828104825741
            },
            "heading": -3.1058320674098177
        },
        {
            "location": {
                "x": 552.676753688161,
                "y": 47.1650569078065
            },
            "heading": -3.1058320674098177
        },
        {
            "location": {
                "x": 588.0048980083698,
                "y": 85.23017942746264
            },
            "heading": -3.09977569436187
        },
        {
            "location": {
                "x": 589.5377396862409,
                "y": 48.59556682087077
            },
            "heading": -3.09977569436187
        }
    ]
}
