name: Project Deploy

on:
  push:
    branches: [ "main" ]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx8g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    name: Assemble artifacts
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version-file: .github/workflows/.java-version

      - name: Configure Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Run Gradle Tasks
        run: ./gradlew site publishImage --parallel
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Fix permissions
        run: |
          chmod -v -R +rX "build/_site" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: build/_site

      - name: (Fail-only) Upload reports
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: reports-core
          path: |
            **/build/reports/**
            **/build/compose/logs/**

  deploy-pages:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  deploy-server:
    name: Deploy server
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7

      - name: Copy deployment configuration files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          rm: true
          strip_components: 1
          source: "deploy"
          target: "~/arcade"
          timeout: 120s

      - name: Deploy latest version of server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd arcade
            docker compose pull server
            docker compose up -d server
            docker image prune -f
